# Generated by Django 4.2.6 on 2023-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_rename_desc_medicine_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='Doctors',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(),
        ),
    ]
